blank_issues_enabled: false

contact_links:
  - name: Discussions
    url: https://github.com/isocroft/laravel-groquel/discussions/new/choose
    about: For questions, discussions, or general technical support from other Laravel users, visit the Discussions page.
